sudo: required

language: python
python:
    - "2.7"
    - "3.6"

services:
    - docker

env:
    - MOZ_HEADLESS=1
addons:
    firefox: latest

before_install:
    - cd tests
    - pip install --upgrade pip
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.23.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - geckodriver --version
    - docker pull selenium/node-firefox:3.14.0
    - docker pull selenium/hub:3.14.0
    - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.14.0
    - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox:3.14.0

install:
    - pip install -r requirements.txt
    - cd ..
    - make all

script:
    - cd tests
#    - python tests.py
    - for f in *.py; do python "$f"; done
    - cat geckodriver.log
