sudo: required

language:
    - php
    - python

python:
    - "2.7"
    - "3.6"

services:
    - docker

before_install:
    - pip install --upgrade pip
    - docker pull selenium/node-firefox:3.8.1-francium
    - docker pull selenium/hub:3.8.1-francium
    - docker run -d -p 4444:4444 --name selenium-hub selenium/hub:3.8.1-francium
    - docker run -d --link selenium-hub:hub --name selenium-node-firefox -v /dev/shm:/dev/shm selenium/node-firefox:3.8.1-francium

install:
    - pip install -r requirements.txt

script:
    - make all
    - python tests.py
