version: '3'
services:
  php-apache:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html:z
    links:
      - 'mariadb'

  mariadb:
    image: mariadb:10.1
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: 'Europe/Paris'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: 'cdp25'
      MYSQL_PASSWORD: 'r8T44vN9qQ'
      MYSQL_DATABASE: 'scrum'
    ports:
      - 8889:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

volumes:
  mariadb:
