version: '3'
services:
  # Créer le serveur Apache avec PHP comme défini par le Dockerfile
  # Disponible à http://localhost[:80]/
  php-apache:
    build:
      context: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html:z
    # MariaDB doit être créée avant ce serveur
    links:
      - 'mariadb'

      #Disponible à l'adresse : http://localhost:3306
  mariadb:
    image: mariadb:10.1
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      TZ: 'Europe/Paris'

      # Permettre l'authentication facile pour utiliser phpMyAdmin
      #   Serveur: mariadb
      #   Utilisateur: root
      #   Laissez le mot de passe vide
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

      # Identifiants utilisés par PHP
      MYSQL_USER: 'cdp25'
      MYSQL_PASSWORD: 'r8T44vN9qQ'
      MYSQL_DATABASE: 'scrum'
    ports:
      - 3306:3306

  # Disponible à http://localhost:8080/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions

# Faire persister la base de données dans une volume Docker
volumes:
  mariadb:
