version: '3'
services:
    php-apache:
        build:
            context: ./php-apache
        ports:
            - 80:80
        volumes:
            - ./DocumentRoot:/var/www/html:z
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:10.1
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: 'Europe/Paris'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'test'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'testdb'
        ports:
            - 8889:3306

volumes:
    mariadb:

